[package]
name = "indradb"
version = "1.1.0"
authors = ["Yusuf Simonson <simonson@gmail.com>"]
description = "A graph database server"
homepage = "https://indradb.github.io"
repository = "https://github.com/indradb/indradb"
keywords = ["graph", "database"]
categories = ["database", "database-implementations"]
license = "MPL-2.0"
build = "build.rs"
edition = "2018"

[badges]
travis-ci = { repository = "indradb/indradb", branch = "master" }

[features]
bench-suite = ["indradb-lib/bench-suite"]
test-suite = ["indradb-lib/test-suite"]

[[bin]]
name = "indradb"
path = "src/server/main.rs"

[lib]
name = "common"
path = "src/common/lib.rs"

[dependencies]
failure = "0.1.8"
serde_json = "^1.0.57"
uuid = "0.8.1"
capnp = "0.13.3"
capnp-rpc = "0.13.1"
futures = "0.3.5"
async-std = { version = "1.6.4", features = ["unstable"] }
num_cpus = "1.13.0"
chrono = "0.4.15"
dummy_cli_parser = { git = "https://github.com/duanjp8617/dummy_cli_parser.git", branch = "master" }


[dependencies.indradb-lib]
path = "../lib"
version = "1.1.0"
features = ["test-suite", "rocksdb-datastore", "sled-datastore"]

[build-dependencies]
capnpc = "0.13.1"
